name: deen_care
description: "Ton allié pour Mémoriser le Coran"
publish_to: 'none'
version: 1.1.0+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  cloud_functions: ^6.0.0
  
  # État
  provider: ^6.1.5
  
  # UI/Navigation
  go_router: ^16.0.0
  
  # HTTP & API
  http: ^1.4.0
  dio: ^5.7.0
  
  # Agora
  agora_chat_sdk: ^1.3.3
  agora_rtc_engine: ^6.5.2
  permission_handler: ^12.0.1  # Package for managing runtime permissions

  # Utils
  intl: ^0.20.2
  url_launcher: ^6.3.2
  flutter_dotenv: ^5.1.0

  # Calendar
  table_calendar: ^3.0.9

  # Dev
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/Deen-care_app-logo.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - .env
