// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeKuNKe15eOJrPvpc9lZawP98ajj-DV4w',
    appId: '1:630412207790:web:1988a0a750e3a50b092f3f',
    messagingSenderId: '630412207790',
    projectId: 'caunvo',
    authDomain: 'caunvo.firebaseapp.com',
    storageBucket: 'caunvo.firebasestorage.app',
    measurementId: 'G-QC5LCH9E7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJgywuYNS8pFx3TWQz9j1G7XFEL46QZLc',
    appId: '1:630412207790:android:a5f0d4bc54839061092f3f',
    messagingSenderId: '630412207790',
    projectId: 'caunvo',
    storageBucket: 'caunvo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADWu_833ZJKMR0zWwmwGr-gSUed9SPR3k',
    appId: '1:630412207790:ios:f89541957f0e01ce092f3f',
    messagingSenderId: '630412207790',
    projectId: 'caunvo',
    storageBucket: 'caunvo.firebasestorage.app',
    iosBundleId: 'care.deen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADWu_833ZJKMR0zWwmwGr-gSUed9SPR3k',
    appId: '1:630412207790:ios:20010339e6997c9e092f3f',
    messagingSenderId: '630412207790',
    projectId: 'caunvo',
    storageBucket: 'caunvo.firebasestorage.app',
    iosBundleId: 'fr.protelec.caunvo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeKuNKe15eOJrPvpc9lZawP98ajj-DV4w',
    appId: '1:630412207790:web:7cfaa33247b870b2092f3f',
    messagingSenderId: '630412207790',
    projectId: 'caunvo',
    authDomain: 'caunvo.firebaseapp.com',
    storageBucket: 'caunvo.firebasestorage.app',
    measurementId: 'G-GVYQT9H334',
  );

}